/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import prgs.conexion;

/**
 *
 * @author utic
 */
public class cliente extends javax.swing.JFrame {
  conexion  miconex = new conexion();
  javax.swing.table.DefaultTableModel cursor;// se crea el cursor  

    /**
     * Creates new form cliente
     */
    public cliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        cursor = (javax.swing.table.DefaultTableModel)grilla_cliente.getModel();      
        this.setLocationRelativeTo(null);//centrar 
        cargar_grilla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tx_codigo = new javax.swing.JTextField();
        tx_apellido = new javax.swing.JTextField();
        tx_CI = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tx_nombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tx_id_nacionalidad = new javax.swing.JTextField();
        jb_cancelar = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();
        jb_grabar = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();
        jb_agregar8 = new javax.swing.JButton();
        tx_nacionalidad = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla_cliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("APELLIDO");

        jLabel8.setText("NOMBRE");

        tx_codigo.setEnabled(false);
        tx_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_codigoActionPerformed(evt);
            }
        });

        tx_apellido.setEnabled(false);

        tx_CI.setEnabled(false);

        jLabel9.setText("C.I");

        jLabel10.setText("CODIGO");

        tx_nombre.setEnabled(false);

        jLabel11.setText("NACIONALIDAD");

        tx_id_nacionalidad.setEnabled(false);
        tx_id_nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_id_nacionalidadActionPerformed(evt);
            }
        });
        tx_id_nacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_id_nacionalidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx_id_nacionalidadKeyTyped(evt);
            }
        });

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/cancelar.png"))); // NOI18N
        jb_cancelar.setText("CANCELAR");
        jb_cancelar.setEnabled(false);
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });

        jb_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/salir1 (1).png"))); // NOI18N
        jb_salir.setText("SALIR");
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });

        jb_grabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/guardar.png"))); // NOI18N
        jb_grabar.setText("GRABAR");
        jb_grabar.setEnabled(false);
        jb_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_grabarActionPerformed(evt);
            }
        });

        jb_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/editar.png"))); // NOI18N
        jb_editar.setText("EDITAR");
        jb_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_editarActionPerformed(evt);
            }
        });

        jb_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/borrar.png"))); // NOI18N
        jb_borrar.setText("BORRAR");
        jb_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarActionPerformed(evt);
            }
        });

        jb_agregar8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/agregar.png"))); // NOI18N
        jb_agregar8.setText("AGREGAR");
        jb_agregar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregar8ActionPerformed(evt);
            }
        });

        tx_nacionalidad.setEnabled(false);
        tx_nacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx_nacionalidadKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("CLIENTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        grilla_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "APELLIDO", "CI", "NACIONALIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grilla_cliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tx_CI, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tx_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tx_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tx_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tx_id_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tx_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_borrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_grabar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_agregar8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_agregar8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tx_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tx_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tx_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tx_CI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tx_id_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(tx_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_grabar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_codigoActionPerformed
        buscar_cod();
    }//GEN-LAST:event_tx_codigoActionPerformed

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        des_text();
        hab_botones();
        clear_text();
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
        dispose();
    }//GEN-LAST:event_jb_salirActionPerformed

    private void jb_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_grabarActionPerformed
        grabar();
        des_text();
        hab_botones();
        clear_text();
        cargar_grilla(); 

    }//GEN-LAST:event_jb_grabarActionPerformed

    private void jb_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_editarActionPerformed
       operacion= "editar";
       
       des_botones();
        
       this.tx_codigo.setEnabled(true);
       this.tx_codigo.requestFocus();
    }//GEN-LAST:event_jb_editarActionPerformed

    private void jb_agregar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregar8ActionPerformed
       operacion= "agregar";
       generar_id();
       hab_text();
       des_botones();
    }//GEN-LAST:event_jb_agregar8ActionPerformed

    private void jb_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarActionPerformed
       operacion="borrar";
       
       des_botones();
       
       this.tx_codigo.setEnabled(true);
       this.tx_codigo.requestFocus();
    }//GEN-LAST:event_jb_borrarActionPerformed

    private void tx_id_nacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_id_nacionalidadActionPerformed
        buscar_nacionalidad();
    }//GEN-LAST:event_tx_id_nacionalidadActionPerformed

    private void tx_id_nacionalidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_id_nacionalidadKeyPressed
          //para llamar al buscador
        //JOptionPane.showMessageDialog(null, "codigo de la tecla presionada-->"+ evt.getKeyCode(), "Atencion", JOptionPane.ERROR_MESSAGE);
       
        if(evt.getKeyCode()==113) // F2
        { // presiona F2
            JTextField[] tfParam = new JTextField[2];

            tfParam[0] = this.tx_id_nacionalidad;
            tfParam[1] = this.tx_nacionalidad;

            String sql = "SELECT nac_id AS codigo,nac_descri AS descripcion FROM nacionalidad WHERE  nac_descri LIKE  ";
            Buscador pp = new Buscador(sql , new String[]{"Codigo", "Nacionalidad"},2, tfParam);
            pp.setTitle("Buscar Nacionalidad");
            pp.setVisible(true);
        }
       
    }//GEN-LAST:event_tx_id_nacionalidadKeyPressed

    private void tx_id_nacionalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_id_nacionalidadKeyTyped
        // validacion solo numeros
        char caracter = evt.getKeyChar();
        if(((caracter < '0') ||
                (caracter > '9')) &&
                (caracter != evt.VK_BACK_SPACE)) 
            
        {
            evt.consume();
        }
    }//GEN-LAST:event_tx_id_nacionalidadKeyTyped

    private void tx_nacionalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_nacionalidadKeyTyped
        // validar solo letras
        int k = (int) evt.getKeyChar();
        if (k > 47 && k < 58) 
	{
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            getToolkit().beep();///el sonido del error
            evt.consume();////mantiene el pulsor al presionar espacio
            JOptionPane.showMessageDialog(null,"No puede Ingresar Numeros");
            tx_nacionalidad.requestFocus();
        }
    }//GEN-LAST:event_tx_nacionalidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cliente().setVisible(true);
            }
        });
    }
    //declarar mis variables
    //bandera para saber que operacion se esta realizando
      private String operacion= "";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable grilla_cliente;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_agregar8;
    private javax.swing.JButton jb_borrar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_editar;
    private javax.swing.JButton jb_grabar;
    private javax.swing.JButton jb_salir;
    private javax.swing.JTextField tx_CI;
    private javax.swing.JTextField tx_apellido;
    private javax.swing.JTextField tx_codigo;
    private javax.swing.JTextField tx_id_nacionalidad;
    private javax.swing.JTextField tx_nacionalidad;
    private javax.swing.JTextField tx_nombre;
    // End of variables declaration//GEN-END:variables

private void hab_text()
{
     this.tx_nombre.setEnabled(true);
     this.tx_apellido.setEnabled(true);
     this.tx_CI.setEnabled(true);
     this.tx_id_nacionalidad.setEnabled(true);
     //habilta los demas text si hay
      this.tx_nombre.requestFocus();
}
private void des_text()
{
     this.tx_nombre.setEnabled(false);
     this.tx_apellido.setEnabled(false);
     this.tx_CI.setEnabled(false);
     this.tx_id_nacionalidad.setEnabled(false);
     this.tx_codigo.setEnabled(false);
     this.tx_nacionalidad.setEnabled(false);
     
}

private void des_botones()
{
     this.jb_grabar.setEnabled(true);
     this.jb_editar.setEnabled(false);
     this.jb_borrar.setEnabled(false);
     this.jb_agregar8.setEnabled(false);
     this.jb_cancelar.setEnabled(true);
     this.jb_salir.setEnabled(false);
              
}

private void hab_botones()
{
    this.jb_grabar.setEnabled(false);
     this.jb_editar.setEnabled(true);
     this.jb_borrar.setEnabled(true);
     this.jb_agregar8.setEnabled(true);
     this.jb_cancelar.setEnabled(false);
     this.jb_salir.setEnabled(true);
              
}

private void clear_text()
{
    tx_codigo.setText("");
    tx_CI.setText(""); 
    tx_apellido.setText(""); 
    tx_nombre.setText(""); 
    tx_nacionalidad.setText(""); 
    tx_id_nacionalidad.setText(""); 
}
private void generar_id()
   {     
       
        try 
        {
            miconex.sentencia = miconex.conexion.createStatement();
            miconex.resultado = miconex.sentencia.executeQuery("SELECT IFNULL(MAX(cli_id),0) + 1  AS nuevo FROM cliente");
            
            //etraer los datos de la variable
            while(miconex.resultado.next()==true)
            {
                this.tx_codigo.setText(miconex.resultado.getString("nuevo"));
            }
        } ///fin generar id
        catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
   
   private void grabar()
   {    if(operacion.equals("agregar"))      
        try { 
            miconex.sentencia = miconex.conexion.createStatement();
            miconex.sentencia.executeUpdate("INSERT INTO cliente(cli_id,cli_nombre,cli_apellido,cli_CI,nac_id)VALUES("+this.tx_codigo.getText()+",'"+this.tx_nombre.getText()+"','"+this.tx_apellido.getText()+"','"+this.tx_CI.getText()+"',"+this.tx_id_nacionalidad.getText()+")");
            
            JOptionPane.showMessageDialog(null, "El registro se ha insertado satisfactoriamente.", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);         
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
   
//ENVIAR UPDATE
        if(operacion.equals("editar")) 
        { 
           try 
            {
                miconex.sentencia = miconex.conexion.createStatement();
                miconex.sentencia.executeUpdate("UPDATE cliente SET cli_nombre = '"+this.tx_nombre.getText()+"',cli_apellido='"+this.tx_apellido.getText()+"',cli_CI='"+this.tx_CI.getText()+"',nac_id="+this.tx_id_nacionalidad.getText()+" WHERE cli_id ="+this.tx_codigo.getText());
                //miconex.sentencia.executeUpdate("UPDATE marca SET mar_descri = '"+this.tx_marca.getText()+"' WHERE mar_id ="+this.tx_codigo.getText());

                JOptionPane.showMessageDialog(null, "El registro se ha modificado satisfactoriamente.", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
            } 
            catch (SQLException ex)
            {
                Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
            }           
        } // fin editar
   
   }
    private void buscar_cod()
    { 
        try {
            boolean encontro = false;
            
            miconex.sentencia = miconex.conexion.createStatement();
            miconex.resultado = miconex.sentencia.executeQuery("SELECT * FROM cliente WHERE cli_id ="+this.tx_codigo.getText());
            
            //etraer los datos de la variable
            while(miconex.resultado.next()==true)
            {
                this.tx_nombre.setText(miconex.resultado.getString("cli_nombre"));
                this.tx_apellido.setText(miconex.resultado.getString("cli_apellido"));
                this.tx_CI.setText(miconex.resultado.getString("cli_CI"));
                this.tx_id_nacionalidad.setText(miconex.resultado.getString("nac_id"));
                
                    
                encontro = true;
            }
            
            if(encontro==true)
            {
                if(operacion.equals("borrar"))
                {    
                    int respuesta = JOptionPane.showConfirmDialog(this,"Deseas Borrar el Registro?","Confirmar",JOptionPane.YES_NO_OPTION);
                    if(respuesta == JOptionPane.YES_OPTION)
                    {
                        //borrar
                        miconex.sentencia = miconex.conexion.createStatement();
                        miconex.sentencia.executeUpdate("DELETE FROM cliente WHERE cli_id ="+this.tx_codigo.getText());

                        JOptionPane.showMessageDialog(null, "El registro se ha borrado satisfactoriamente.", "Demosys", JOptionPane.INFORMATION_MESSAGE);

                        hab_botones();
                        des_text();
                        clear_text();
                        cargar_grilla();
                    }
                    else
                    {
                        hab_botones();
                        des_text();
                        clear_text();

                        //this.btn_cancelar.doClick();
                    }
                }// fin borrar    
                
                //caso de editar
                 if(operacion.equals("editar"))
                 { 
                      //habilitar los text
                     this.tx_nombre.setEnabled(true);
                     this.tx_apellido.setEnabled(true);
                     this.tx_CI.setEnabled(true);
                     this.tx_id_nacionalidad.setEnabled(true);
                     
                     
                     this.tx_nombre.requestFocus();
                 }
            } 
            else
            {
                JOptionPane.showMessageDialog(null, "No existe un registro con este codigo!", "Atencion", JOptionPane.ERROR_MESSAGE);
                this.tx_codigo.setText("");
                this.tx_codigo.requestFocus();
            }      
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    private void buscar_nacionalidad()
    { 
        boolean encontro = false;
         
        try {
            miconex.sentencia = miconex.conexion.createStatement();
            miconex.resultado = miconex.sentencia.executeQuery("SELECT * FROM  nacionalidad  WHERE nac_id = "+this.tx_id_nacionalidad.getText());
            
            //etraer los datos de la variable
            while(miconex.resultado.next()==true)
            {
                this.tx_nacionalidad.setText(miconex.resultado.getString("nac_descri"));
                encontro = true;
            }
            
            if(encontro==false)
            {
                 JOptionPane.showMessageDialog(null, "No existe un registro con este codigo de Nacionalidad!", "Atencion", JOptionPane.ERROR_MESSAGE);  
                  this.jb_grabar.setEnabled(false);
                  this.tx_id_nacionalidad.setText("");
                  this.tx_id_nacionalidad.requestFocus();
            } 
            else
            {
                this.jb_grabar.setEnabled(true);
            }    
            
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }  
   private void cargar_grilla()
   {
       limpiar_grilla();
       
       try 
        {
          miconex.sentencia = miconex.conexion.createStatement();
          miconex.resultado = miconex.sentencia.executeQuery("SELECT * FROM cliente");
           //boolean encontro = false;
            
           //etraer los datos de la variable
           while(miconex.resultado.next()==true)
            {
               //tirar a la grilla 
               Object registro[] = new Object[] {miconex.resultado.getString("cli_id"),miconex.resultado.getString("cli_nombre"),miconex.resultado.getString("cli_apellido"),miconex.resultado.getString("cli_CI"),miconex.resultado.getString("nac_id")};
               cursor.addRow(registro);
            }
            
        } catch (SQLException ex) 
        {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
   }// fin carga grilla

  private void limpiar_grilla()
   { 
     for (int posic = grilla_cliente.getRowCount() -1; posic >= 0; posic--)
     {
          cursor.removeRow(posic);
     }  
   }// fin limpiar grilla   

    
}
