/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import prgs.conexion;

/**
 *
 * @author utic
 */
public class marca extends javax.swing.JFrame {
  conexion  miconex = new conexion();
   javax.swing.table.DefaultTableModel cursor;// se crea el cursor  

    /**
     * Creates new form marca
     */
    public marca() {
        initComponents();
        this.setLocationRelativeTo(null);
        cursor = (javax.swing.table.DefaultTableModel)grilla_color.getModel();      
        this.setLocationRelativeTo(null);//centrar 
        cargar_grilla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tx_marca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tx_codigo = new javax.swing.JTextField();
        jb_cancelar2 = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();
        jb_grabar = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();
        jb_agregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla_color = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CODIGO");

        tx_marca.setEnabled(false);

        jLabel2.setText("MARCA");

        tx_codigo.setEnabled(false);
        tx_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_codigoActionPerformed(evt);
            }
        });

        jb_cancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/cancelar.png"))); // NOI18N
        jb_cancelar2.setText("CANCELAR");
        jb_cancelar2.setEnabled(false);
        jb_cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelar2ActionPerformed(evt);
            }
        });

        jb_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/salir1 (1).png"))); // NOI18N
        jb_salir.setText("SALIR");
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });

        jb_grabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/guardar.png"))); // NOI18N
        jb_grabar.setText("GRABAR");
        jb_grabar.setEnabled(false);
        jb_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_grabarActionPerformed(evt);
            }
        });

        jb_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/editar.png"))); // NOI18N
        jb_editar.setText("EDITAR");
        jb_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_editarActionPerformed(evt);
            }
        });

        jb_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/borrar.png"))); // NOI18N
        jb_borrar.setText("BORRAR");
        jb_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarActionPerformed(evt);
            }
        });

        jb_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/agregar.png"))); // NOI18N
        jb_agregar.setText("AGREGAR");
        jb_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setBackground(new java.awt.Color(0, 0, 204));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("MARCA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        grilla_color.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "MARCA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grilla_color);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tx_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jb_grabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jb_cancelar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tx_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tx_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jb_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_grabar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_cancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_codigoActionPerformed
         buscar_cod();
    }//GEN-LAST:event_tx_codigoActionPerformed

    private void jb_cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelar2ActionPerformed
        des_text();
        hab_botones();
        clear_text();
    }//GEN-LAST:event_jb_cancelar2ActionPerformed

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
        dispose();
    }//GEN-LAST:event_jb_salirActionPerformed

    private void jb_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_grabarActionPerformed
        grabar();
        des_text();
        hab_botones();
        clear_text();
        cargar_grilla();
    }//GEN-LAST:event_jb_grabarActionPerformed

    private void jb_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_editarActionPerformed
       operacion= "editar";
       
       des_botones();
        
       this.tx_codigo.setEnabled(true);
       this.tx_codigo.requestFocus();
    }//GEN-LAST:event_jb_editarActionPerformed

    private void jb_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarActionPerformed
       operacion= "agregar";
       generar_id();
       hab_text();
       des_botones();
    }//GEN-LAST:event_jb_agregarActionPerformed

    private void jb_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarActionPerformed
       operacion="borrar";
       
       des_botones();
       
       this.tx_codigo.setEnabled(true);
       this.tx_codigo.requestFocus();
    }//GEN-LAST:event_jb_borrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new marca().setVisible(true);
            }
        });
    }
    //declarar mis variables
    //bandera para saber que operacion se esta realizando
      private String operacion= "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable grilla_color;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_borrar;
    private javax.swing.JButton jb_cancelar2;
    private javax.swing.JButton jb_editar;
    private javax.swing.JButton jb_grabar;
    private javax.swing.JButton jb_salir;
    private javax.swing.JTextField tx_codigo;
    private javax.swing.JTextField tx_marca;
    // End of variables declaration//GEN-END:variables
private void hab_text()
{
     this.tx_marca.setEnabled(true);
     
     //habilta los demas text si hay
      this.tx_marca.requestFocus();
}
private void des_text()
{
     this.tx_marca.setEnabled(false);
     this.tx_codigo.setEnabled(false);
}

private void des_botones()
{
     this.jb_grabar.setEnabled(true);
     this.jb_editar.setEnabled(false);
     this.jb_borrar.setEnabled(false);
     this.jb_agregar.setEnabled(false);
     this.jb_cancelar2.setEnabled(true);
     this.jb_salir.setEnabled(false);
              
}

private void hab_botones()
{
     this.jb_grabar.setEnabled(false);
     this.jb_editar.setEnabled(true);
     this.jb_borrar.setEnabled(true);
     this.jb_agregar.setEnabled(true);
     this.jb_cancelar2.setEnabled(false);
     this.jb_salir.setEnabled(true);
              
}

private void clear_text()
{
    tx_codigo.setText("");
    tx_marca.setText(""); 
}
 private void generar_id()
   {     
       
        try 
        {
            miconex.sentencia = miconex.conexion.createStatement();
            miconex.resultado = miconex.sentencia.executeQuery("SELECT IFNULL(MAX(mar_id),0) + 1  AS nuevo FROM marca");
            
            //etraer los datos de la variable
            while(miconex.resultado.next()==true)
            {
                this.tx_codigo.setText(miconex.resultado.getString("nuevo"));
            }
        } ///fin generar id
        catch (SQLException ex) {
            Logger.getLogger(marca.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
   
   private void grabar()
   {    if(operacion.equals("agregar")) 
        try {
            miconex.sentencia = miconex.conexion.createStatement();
            miconex.sentencia.executeUpdate("INSERT INTO marca(mar_id,mar_descri) VALUES("+this.tx_codigo.getText()+",'"+this.tx_marca.getText()+"')");
            
            JOptionPane.showMessageDialog(null, "El registro se ha insertado satisfactoriamente.", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);         
        } catch (SQLException ex) {
            Logger.getLogger(marca.class.getName()).log(Level.SEVERE, null, ex);
        }
   //ENVIAR UPDATE
        if(operacion.equals("editar")) 
        { 
           try 
            {
                miconex.sentencia = miconex.conexion.createStatement();
                //miconex.sentencia.executeUpdate("UPDATE grupos SET gru_descri = '"+this.txt_nombre.getText()+"',con_cod="+this.txt_con_cod.getText()+" WHERE pai_cod ="+this.txt_cod.getText());
                miconex.sentencia.executeUpdate("UPDATE marca SET mar_descri = '"+this.tx_marca.getText()+"' WHERE mar_id ="+this.tx_codigo.getText());

                JOptionPane.showMessageDialog(null, "El registro se ha modificado satisfactoriamente.", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
            } 
            catch (SQLException ex)
            {
                Logger.getLogger(marca.class.getName()).log(Level.SEVERE, null, ex);
            }           
        } // fin editar
   
   }
    private void buscar_cod()
    { 
        try { 
            boolean encontro = false;
            
            miconex.sentencia = miconex.conexion.createStatement();
            miconex.resultado = miconex.sentencia.executeQuery("SELECT * FROM marca WHERE mar_id ="+this.tx_codigo.getText());
            
            //etraer los datos de la variable
            while(miconex.resultado.next()==true)
            {
                this.tx_marca.setText(miconex.resultado.getString("mar_descri"));
                //aca los demas atributos
                //this.txt_con_cod.setText(miconex.resultado.getString("xxx"));
                    
                encontro = true;
            }
            
            if(encontro==true)
            {
                if(operacion.equals("borrar"))
                {    
                    int respuesta = JOptionPane.showConfirmDialog(this,"Deseas Borrar el Registro?","Confirmar",JOptionPane.YES_NO_OPTION);
                    if(respuesta == JOptionPane.YES_OPTION)
                    {
                        //borrar
                        miconex.sentencia = miconex.conexion.createStatement();
                        miconex.sentencia.executeUpdate("DELETE FROM marca WHERE mar_id ="+this.tx_codigo.getText());

                        JOptionPane.showMessageDialog(null, "El registro se ha borrado satisfactoriamente.", "Demosys", JOptionPane.INFORMATION_MESSAGE);

                        hab_botones();
                        des_text();
                        clear_text();
                        cargar_grilla();
                    }
                    else
                    {
                        hab_botones();
                        des_text();
                        clear_text();

                        //this.btn_cancelar.doClick();
                    }
                }// fin borrar    
                
                //caso de editar
                 if(operacion.equals("editar"))
                 { 
                      //habilitar los text
                     this.tx_marca.setEnabled(true);
                     
                     
                     this.tx_marca.requestFocus();
                 }
            } 
            else
            {
                JOptionPane.showMessageDialog(null, "No existe un registro con este codigo!", "Atencion", JOptionPane.ERROR_MESSAGE);
                this.tx_codigo.setText("");
                this.tx_codigo.requestFocus();
            }      
        } catch (SQLException ex) {
            Logger.getLogger(marca.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    private void cargar_grilla()
   {
       limpiar_grilla();
       
       try 
        {
          miconex.sentencia = miconex.conexion.createStatement();
          miconex.resultado = miconex.sentencia.executeQuery("SELECT * FROM marca");
           //boolean encontro = false;
            
           //etraer los datos de la variable
           while(miconex.resultado.next()==true)
            {
               //tirar a la grilla 
               Object registro[] = new Object[] {miconex.resultado.getString("mar_id"),miconex.resultado.getString("mar_descri")};
               cursor.addRow(registro);
            }
            
        } catch (SQLException ex) 
        {
            Logger.getLogger(marca.class.getName()).log(Level.SEVERE, null, ex);
        }
   }// fin carga grilla

  private void limpiar_grilla()
   { 
     for (int posic = grilla_color.getRowCount() -1; posic >= 0; posic--)
     {
          cursor.removeRow(posic);
     }  
   }// fin limpiar grilla   
}
  


